name: network config manager CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3
    - name: install update
      run: sudo apt-get update -y; sudo apt-get upgrade -y
    - name: install packages
      run: sudo apt-get install python3 python3-pip python3-dev python3-setuptools build-essential python3-sphinx ninja-build glib-2.0-dev libudev-dev libyaml-dev libsystemd-dev clang sudo libjson-c-dev libglib2.0-dev python3-dev libffi-dev libssl-dev systemd libsystemd-dev libmnl-dev libnftnl-dev nftables libnftables-dev libcmocka-dev -y
    - name: update python
      run: sudo pip3 install -U meson pytest
    - name: install config parser
      run: pip3 install configparser
    - name: make
      run: meson --prefix=/usr -Dtests=true -Dnftables=true build; ninja -C build; sudo ninja -C build install; sudo make install-tests
    - name: run tests
      run: sudo cp -r tests /run/network-config-manager-ci; sudo pytest -v -s /run/network-config-manager-ci/network-config-manager-tests.py
    - name: build without nftables and tests
      run: meson --prefix=/usr build-ex; ninja -C build-ex
    - name: build clang
      run: CC=clang  meson setup build-clang; ninja -C build-clang
