name: network config manager CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install update
      run: sudo apt-get update -y
    - name: install packages
      run: sudo apt-get install python3 python3-pip python3-dev python3-setuptools build-essential python3-sphinx python-configparser ninja-build glib-2.0-dev libudev-dev libyaml-dev libsystemd-dev clang sudo libglib2.0-dev python3-dev libffi-dev libssl-dev systemd libsystemd-dev -y
    - name: update python
      run: sudo pip3 install -U meson pytest
    - name: make
      run: meson build; ninja -C build; sudo ninja -C build install
    - name: run tests
      run: sudo cp -r tests /run/network-config-manager-ci; sudo pytest -v -s /run/network-config-manager-ci/network-config-manager-tests.py
    - name: build clang
      run: CC=clang  meson build-clang; ninja -C build-clang
